version: '3.5'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: change_me_user
      MYSQL_PASSWORD: change_me_pass
      MYSQL_ROOT_PASSWORD: change_me_root_pass
    expose:
      - "3306"

  simulate:
    build:
      context: .
      dockerfile: ./mysql-Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5678:5678"